### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by kenyarmosh** [monsterkodi/tree-view-filter#2]
**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tree-view-filter](https://github.com/monsterkodi/tree-view-filter) package, v0.2.14

### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

```
At /Users/ky/.atom/packages/tree-view-filter/lib/tree-view-filter-view.coffee:41

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  at Error (native)
  at TreeViewFilterView.module.exports.TreeViewFilterView.hide (/Users/ky/.atom/packages/tree-view-filter/lib/tree-view-filter-view.coffee:41:15)
  at atom-workspace.<anonymous> (/Users/ky/.atom/packages/tree-view-filter/lib/tree-view-filter.coffee:46:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:07.3.0 core:close (a.)
     -0:00.9.0 tree-view:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ],
  },
  "tree-view-filter": {
    "liveUpdate": true
  }
}
```

### Installed Packages

```coffee
# User
tree-view-filter, v0.2.14
typewriter, v0.3.3
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by monsterkodi** [comment]
Thanks for reporting this. Will be fixed soon.

**Comment by monsterkodi** [comment]
The issue should be fixed in the latest version. Thanks again.
