### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by riguy724** [monsterkodi/tree-view-filter#6]
1. Install treeview filter
2. Search for something

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [tree-view-filter](https://github.com/monsterkodi/tree-view-filter) package, v0.3.7

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:772

TypeError: Cannot read property 'split' of null
  at Minimatch.match (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/minimatch/minimatch.js:706:8)
  at minimatch (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/minimatch/minimatch.js:99:42)
  at Object.module.exports.TreeViewFilter.isFileNameFiltered (/Users/chris/.atom/packages/tree-view-filter/lib/tree-view-filter.coffee:95:16)
  at Object.module.exports.TreeViewFilter.setFilterPatterns (/Users/chris/.atom/packages/tree-view-filter/lib/tree-view-filter.coffee:79:44)
  at Object.module.exports.TreeViewFilter.setFilterPattern (/Users/chris/.atom/packages/tree-view-filter/lib/tree-view-filter.coffee:65:10)
  at Object.module.exports.TreeViewFilter.editorConfirmed (/Users/chris/.atom/packages/tree-view-filter/lib/tree-view-filter.coffee:102:26)
  at Object.module.exports.TreeViewFilter.editorChanged (/Users/chris/.atom/packages/tree-view-filter/lib/tree-view-filter.coffee:106:14)
  at /Users/chris/.atom/packages/tree-view-filter/lib/tree-view-filter.coffee:40:53
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1592:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1551:12)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:404:27)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:64:24
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:647:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:552:12)
  at Selection.module.exports.Selection.insertText (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/selection.js:476:43)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:745:29
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:767:18)
  at TextEditor.module.exports.TextEditor.transact (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1168:26)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2037:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1999:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:447:35)
  at HTMLDivElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
  3x -0:24.6.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:23.7.0 nerd-treeview:open-tab-stay (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.9.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.6.0 nerd-treeview:open-tab-stay (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:21.4.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.6.0 nerd-treeview:open-tab-stay (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:19.9.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:18.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:18.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:18.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:close (atom-text-editor.editor.is-focused)
     -0:07.1.0 command-palette:toggle (div.settings-view.pane-item)
  3x -0:06.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 tree-view-filter:activate (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "nerd-treeview"
    ]
  },
  "tree-view-filter": {
    "liveUpdate": true
  }
}
```

### Installed Packages

```coffee
# User
file-type-icons, v0.7.3
linter, v1.9.0
nerd-treeview, v0.3.1
symbols-tree-view, v0.10.1
tree-view-filter, v0.3.7
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by monsterkodi** [comment]
Hello riguy,
thanks for your bug report.
I am using the same versions of atom and the filter package, but I can't reproduce the problem, even if I download atom via brew.
Your stack trace suggests that the filter module uses the minimatch package from an unrelated module.  
Please try to uninstall the treeviewfilter module and re-install it again.
(It would be interesting to see the output of 'npm ls' in your ~/.atom/packages/tree-view-filter folder before and after you do that).

**Comment by riguy724** [comment]
Hey so, I found the problem here. It seems that the git status or git branches packages for atom modify some of the DOM in the treeview.  Because the parsing for the list of files to filter happens by matching and extracting data from the dom using selectors, it returns empty and throws an error, things work fine if I uninstall those other two packages though, it does make you wonder if there might be a more compatible way of accessing and filtering the file list in treeview though.

**Comment by monsterkodi** [comment]
yes, there would be a better way to do it, but it would require changes to the tree-view package itself and that doesn't seem very likely to happen. I will check the problem in conjunction with the git packages you mentioned. maybe I can find a workaround. Thanks again for reporting this.

**Comment by monsterkodi** [comment]
ok, it seems to be the tree-view-git-branch package, the status one works fine. I guess I can fix that.

**Comment by monsterkodi** [comment]
It was a very easy fix. I pushed a new version. Please let me know if it doesn't work.

**Comment by riguy724** [comment]
yupp!  working great :+1:

**Comment by monsterkodi** [comment]
cool. thanks for reporting this.
