### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by PipC** [monsterkodi/tree-view-filter#9]
[Enter steps to reproduce:]

1. When "Activate/Toggle tree view from [Packages] menu" 
2. Error occurs

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [tree-view-filter](https://github.com/monsterkodi/tree-view-filter) package 0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of null

```
At U:\.atom\packages\tree-view-filter\lib\tree-view-filter-view.coffee:43

TypeError: Cannot read property 'style' of null
    at TreeViewFilterView.module.exports.TreeViewFilterView.hide (/packages/tree-view-filter/lib/tree-view-filter-view.coffee:43:14)
    at TreeViewFilterView.module.exports.TreeViewFilterView.deactivate (/packages/tree-view-filter/lib/tree-view-filter-view.coffee:52:10)
    at Object.toggle (/packages/tree-view-filter/lib/tree-view-filter.coffee:155:19)
    at /packages/tree-view-filter/lib/tree-view-filter.coffee:67:99)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:1286:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.0/resources/app/src/application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:31 tree-view-filter:activate (div.tool-panel.tree-view)
     -0:10.3.0 tree-view-filter:toggle (div.panels-item)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-alignment 0.13.0 
atom-beautify 0.29.24 
atom-color-highlight 3.0.8 
atom-grails 1.0.1 
browser-plus 0.0.87 
format-sql 0.3.0 
highlight-selected 0.13.1 
language-apache 1.7.0 
language-awk 0.1.12 
language-batch 0.4.0 
language-groovy 0.7.0 
language-tsql 0.19.0 
language-vue 0.21.2 
language-vue-component 0.5.0 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
qolor 0.4.1 
tree-view-filter 0.4.1 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by monsterkodi** [comment]
Hello PipC,
it should be fixed in v0.4.3, please let me know if not.
Thanks for reporting this.
